<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ETS2LA\ETS2LA.Shared\ETS2LA.Shared.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="..\ETS2LA\ETS2LA.Backend\ETS2LA.Backend.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="..\ETS2LA\ETS2LA.Game\ETS2LA.Game.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="..\ETS2LA\ETS2LA.Overlay\ETS2LA.Overlay.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="..\ETS2LA\ETS2LA.State\ETS2LA.State.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="..\ETS2LA\ETS2LA.UI\ETS2LA.UI.csproj"><Private>false</Private></ProjectReference>
  </ItemGroup>
</Project>
